<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageVersion Include="MinVer" Version="6.0.0" />
    <PackageVersion Include="SharpCompress" Version="0.39.0" />
    <PackageVersion Include="SkiaSharp" Version="2.88.8" />
  </ItemGroup>

</Project>
