using ShockwaveFlash.Avm1.Serialization;
using ShockwaveFlash.Avm1.Serialization.Metadata;
using ShockwaveFlash.Tests.Models.Langs;

namespace ShockwaveFlash.Tests.Serialization;

[Avm1Serializable(typeof(AlignmentFile))]
[Avm1Serializable(typeof(AudioFile))]
[Avm1Serializable(typeof(ClassesFile))]
[Avm1Serializable(typeof(CraftsFile))]
[Avm1Serializable(typeof(DialogFile))]
[Avm1Serializable(typeof(DungeonsFile))]
[Avm1Serializable(typeof(EffectsFile))]
[Avm1Serializable(typeof(EmotesFile))]
[Avm1Serializable(typeof(FightChallengeFile))]
[Avm1Serializable(typeof(GuildsFile))]
[Avm1Serializable(typeof(HintsFile))]
[Avm1Serializable(typeof(HousesFile))]
[Avm1Serializable(typeof(InteractiveObjectsFile))]
[Avm1Serializable(typeof(ItemsFile))]
[Avm1Serializable(typeof(ItemsetsFile))]
[Avm1Serializable(typeof(ItemstatsFile))]
[Avm1Serializable(typeof(JobsFile))]
[Avm1Serializable(typeof(KbFile))]
[Avm1Serializable(typeof(MapsFile))]
[Avm1Serializable(typeof(MonstersFile))]
[Avm1Serializable(typeof(NamesFile))]
[Avm1Serializable(typeof(NpcFile))]
[Avm1Serializable(typeof(PvpFile))]
[Avm1Serializable(typeof(QuestsFile))]
[Avm1Serializable(typeof(RanksFile))]
[Avm1Serializable(typeof(RidesFile))]
[Avm1Serializable(typeof(ScriptsFile))]
[Avm1Serializable(typeof(ServersFile))]
[Avm1Serializable(typeof(ShortcutsFile))]
[Avm1Serializable(typeof(SkillsFile))]
[Avm1Serializable(typeof(SpeakingItemsFile))]
[Avm1Serializable(typeof(SpellsFile))]
[Avm1Serializable(typeof(StatesFile))]
[Avm1Serializable(typeof(SubtitlesFile))]
[Avm1Serializable(typeof(TimezonesFile))]
[Avm1Serializable(typeof(TitlesFile))]
[Avm1Serializable(typeof(TtgFile))]
public partial class DofusLangContext : Avm1SerializerContext;
