using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis.CSharp;
using ShockwaveFlash.SourceGenerators.Avm1.Models;

namespace ShockwaveFlash.SourceGenerators.Avm1;

internal static class Avm1SerializableEmitter
{
    private const string Types = "global::ShockwaveFlash.Avm1.Types";
    private const string ObjectType = Types + ".Avm1Object";
    private const string ArrayType = Types + ".Avm1Array";
    private const string StringType = Types + ".Avm1String";
    private const string NumberType = Types + ".Avm1Number";
    private const string BooleanType = Types + ".Avm1Boolean";
    private const string ValueType = Types + ".Avm1Value";
    private const string Interface = "global::ShockwaveFlash.Avm1.Serialization.IAvm1Serializable";
    private const string ExceptionType = "global::ShockwaveFlash.Avm1.Exceptions.Avm1SerializationException";
    private const string GeneratedCode = "[global::System.CodeDom.Compiler.GeneratedCode(\"ShockwaveFlash.SourceGenerators\", \"1.0.0\")]";

    public static string Emit(Avm1TypeModel model)
    {
        var builder = new IndentedStringBuilder()
            .AppendIndentedLine("// <auto-generated/>")
            .AppendIndentedLine("#nullable enable")
            .AppendLine();

        if (model.Namespace is not null)
            builder
                .AppendIndentedLine($"namespace {model.Namespace};")
                .AppendLine();

        var scopes = new Stack<IDisposable>();

        foreach (var containing in model.ContainingTypes)
        {
            builder.AppendIndentedLine($"partial {containing}");
            scopes.Push(builder.CreateScope());
        }

        builder.AppendIndentedLine($"partial {model.TypeKeyword} {model.TypeName} : {Interface}<{model.TypeName}>");
        scopes.Push(builder.CreateScope());

        EmitGlobalName(builder, model);
        builder.AppendLine();
        EmitToAvm1Object(builder, model);
        builder.AppendLine();
        EmitFromAvm1Object(builder, model);

        while (scopes.Count > 0)
            scopes.Pop().Dispose();

        return builder.ToString();
    }

    private static void EmitGlobalName(IndentedStringBuilder builder, Avm1TypeModel model)
    {
        var value = model.GlobalName is null ? "null" : Literal(model.GlobalName);

        builder
            .AppendIndentedLine(GeneratedCode)
            .AppendIndentedLine($"public static string? Avm1GlobalName => {value};");
    }

    private static void EmitToAvm1Object(IndentedStringBuilder builder, Avm1TypeModel model)
    {
        builder
            .AppendIndentedLine(GeneratedCode)
            .AppendIndentedLine($"public {ObjectType} ToAvm1Object()");

        using (builder.CreateScope())
        {
            builder
                .AppendIndentedLine($"var __obj = new {ObjectType}();")
                .AppendIndentedLine("var __members = __obj.Members;");

            foreach (var member in model.Members)
            {
                builder.AppendLine();
                EmitWriteMember(builder, member);
            }

            builder
                .AppendLine()
                .AppendIndentedLine("return __obj;");
        }
    }

    private static void EmitWriteMember(IndentedStringBuilder builder, Avm1MemberModel member)
    {
        var key = Literal(member.Avm1Key);
        var source = $"this.{member.CSharpName}";
        var counter = 0;

        using (builder.CreateScope())
        {
            if (!member.MemberNullable)
            {
                EmitWriteValue(builder, member.Value, source, key, ref counter);
                return;
            }

            var valueScalar = member.Value.Kind == ValueKind.Scalar && member.Value.IsValueType;
            builder.AppendIndentedLine($"if ({source}{(valueScalar ? ".HasValue" : " is not null")})");

            using (builder.CreateScope())
                EmitWriteValue(builder, member.Value, valueScalar ? $"{source}.Value" : source, key, ref counter);
        }
    }

    private static void EmitWriteValue(IndentedStringBuilder builder, ValueSpec spec, string source, string key, ref int counter)
    {
        var value = EmitBuildValue(builder, spec, source, ref counter);
        builder.AppendIndentedLine($"__members[{key}] = {value};");
    }

    private static string EmitBuildValue(IndentedStringBuilder builder, ValueSpec spec, string source, ref int counter)
    {
        if (IsSimple(spec))
            return SimpleToValue(spec, source);

        var id = counter++;

        if (spec.Kind is ValueKind.List or ValueKind.Array)
        {
            var array = $"__array{id}";
            builder
                .AppendIndentedLine($"var {array} = new {ArrayType}();")
                .AppendIndentedLine($"foreach (var __element{id} in {source})");

            using (builder.CreateScope())
            {
                var item = EmitBuildValue(builder, spec.Element!, $"__element{id}", ref counter);
                builder.AppendIndentedLine($"{array}.Items.Add({item});");
            }

            return array;
        }

        var table = $"__table{id}";
        builder
            .AppendIndentedLine($"var {table} = new {ObjectType}();")
            .AppendIndentedLine($"foreach (var __pair{id} in {source})");

        using (builder.CreateScope())
        {
            var value = EmitBuildValue(builder, spec.Element!, $"__pair{id}.Value", ref counter);
            builder.AppendIndentedLine($"{table}.Members[__pair{id}.Key] = {value};");
        }

        return table;
    }

    private static void EmitFromAvm1Object(IndentedStringBuilder builder, Avm1TypeModel model)
    {
        builder
            .AppendIndentedLine(GeneratedCode)
            .AppendIndentedLine($"public static {model.TypeName} FromAvm1Object({ObjectType} source)");

        using (builder.CreateScope())
        {
            builder.AppendIndentedLine("var __members = source.Members;");

            foreach (var member in model.Members)
            {
                builder.AppendLine();
                EmitReadMember(builder, member);
            }

            builder.AppendLine();
            EmitConstruction(builder, model);
        }
    }

    private static void EmitReadMember(IndentedStringBuilder builder, Avm1MemberModel member)
    {
        var key = Literal(member.Avm1Key);
        var local = $"__{member.CSharpName}";
        var counter = 0;
        var initial = member.MemberNullable ? "default!" : InitialValue(member.Value);

        builder.AppendIndentedLine($"{member.DeclaredType} {local} = {initial};");

        using (builder.CreateScope())
        {
            var present = member.Value.Kind switch
            {
                ValueKind.Scalar or ValueKind.Nested => " && !__value.IsNull && !__value.IsUndefined",
                _ => string.Empty,
            };

            builder.AppendIndentedLine($"if (__members.TryGetValue({key}, out var __value){present})");

            using (builder.CreateScope())
                EmitReadValue(builder, member.Value, "__value", local, ref counter);

            if (member.ThrowIfMissing)
            {
                builder.AppendIndentedLine("else");

                using (builder.CreateScope())
                    builder.AppendIndentedLine($"throw new {ExceptionType}({Literal($"AVM1 object is missing required member '{member.Avm1Key}'.")});");
            }
        }
    }

    private static void EmitReadValue(IndentedStringBuilder builder, ValueSpec spec, string source, string target, ref int counter)
    {
        if (IsSimple(spec))
        {
            builder.AppendIndentedLine($"{target} = {SimpleFromValue(spec, source)};");
            return;
        }

        var id = counter++;

        if (spec.Kind is ValueKind.List or ValueKind.Array)
        {
            builder.AppendIndentedLine($"if ({source} is {ArrayType} __source{id})");

            using (builder.CreateScope())
            {
                var list = $"__list{id}";
                builder
                    .AppendIndentedLine($"var {list} = new global::System.Collections.Generic.List<{BuildType(spec.Element!)}>(__source{id}.Items.Count);")
                    .AppendIndentedLine($"foreach (var __item{id} in __source{id}.Items)");

                using (builder.CreateScope())
                    EmitAddElement(builder, spec.Element!, $"__item{id}", list, ref counter);

                builder.AppendIndentedLine($"{target} = {list}{(spec.Kind == ValueKind.Array ? ".ToArray()" : string.Empty)};");
            }

            return;
        }

        builder.AppendIndentedLine($"if ({source} is {ObjectType} __source{id})");

        using (builder.CreateScope())
        {
            var dictionary = $"__dictionary{id}";
            builder
                .AppendIndentedLine($"var {dictionary} = new {BuildType(spec)}(global::System.StringComparer.Ordinal);")
                .AppendIndentedLine($"foreach (var __pair{id} in __source{id}.Members)");

            using (builder.CreateScope())
                EmitReadValue(builder, spec.Element!, $"__pair{id}.Value", $"{dictionary}[__pair{id}.Key]", ref counter);

            builder.AppendIndentedLine($"{target} = {dictionary};");
        }
    }

    private static void EmitAddElement(IndentedStringBuilder builder, ValueSpec element, string source, string list, ref int counter)
    {
        if (IsSimple(element))
        {
            builder.AppendIndentedLine($"{list}.Add({SimpleFromValue(element, source)});");
            return;
        }

        var id = counter++;
        var item = $"__add{id}";
        builder.AppendIndentedLine($"{BuildType(element)} {item} = {InitialValue(element)};");
        EmitReadValue(builder, element, source, item, ref counter);
        builder.AppendIndentedLine($"{list}.Add({item});");
    }

    private static void EmitConstruction(IndentedStringBuilder builder, Avm1TypeModel model)
    {
        if (model.Construction == ConstructionKind.Constructor)
        {
            var arguments = string.Join(", ", model.ConstructorParameterOrder.Select(name => $"__{name}"));
            var initializers = model.Members.Where(m => m.IsSettable && !m.IsConstructorParameter).ToList();

            if (initializers.Count == 0)
            {
                builder.AppendIndentedLine($"return new {model.TypeName}({arguments});");
                return;
            }

            builder.AppendIndentedLine($"return new {model.TypeName}({arguments})");
            EmitInitializer(builder, initializers);
            return;
        }

        var settable = model.Members.Where(m => m.IsSettable).ToList();
        if (settable.Count == 0)
        {
            builder.AppendIndentedLine($"return new {model.TypeName}();");
            return;
        }

        builder.AppendIndentedLine($"return new {model.TypeName}");
        EmitInitializer(builder, settable);
    }

    private static void EmitInitializer(IndentedStringBuilder builder, IReadOnlyList<Avm1MemberModel> members)
    {
        builder.AppendIndentedLine("{");
        builder.Indent();

        foreach (var member in members)
            builder.AppendIndentedLine($"{member.CSharpName} = __{member.CSharpName},");

        builder.Unindent();
        builder.AppendIndentedLine("};");
    }

    private static bool IsSimple(ValueSpec spec) =>
        spec.Kind is ValueKind.Scalar or ValueKind.Nested or ValueKind.Passthrough;

    private static string BuildType(ValueSpec spec) => spec.Kind switch
    {
        ValueKind.List => $"global::System.Collections.Generic.List<{BuildType(spec.Element!)}>",
        ValueKind.Array => $"{BuildType(spec.Element!)}[]",
        ValueKind.Dictionary => $"global::System.Collections.Generic.Dictionary<string, {BuildType(spec.Element!)}>",
        _ => spec.TypeFqn,
    };

    private static string InitialValue(ValueSpec spec) => spec.Kind switch
    {
        ValueKind.List => $"new {BuildType(spec)}()",
        ValueKind.Array => $"global::System.Array.Empty<{BuildType(spec.Element!)}>()",
        ValueKind.Dictionary => $"new {BuildType(spec)}(global::System.StringComparer.Ordinal)",
        _ => "default!",
    };

    private static string SimpleToValue(ValueSpec spec, string expression) => spec.Kind switch
    {
        ValueKind.Nested => $"({expression}).ToAvm1Object()",
        ValueKind.Passthrough => expression,
        _ => spec.Conv switch
        {
            ConvKind.String => $"new {StringType}({expression})",
            ConvKind.Boolean => $"new {BooleanType}({expression})",
            ConvKind.Number => $"new {NumberType}((double)({expression}))",
            ConvKind.Enum => $"new {NumberType}((double)(long)({expression}))",
            _ => $"{ValueType}.Undefined",
        },
    };

    private static string SimpleFromValue(ValueSpec spec, string expression) => spec.Kind switch
    {
        ValueKind.Nested => $"{spec.TypeFqn}.FromAvm1Object({expression}.AsObject)",
        ValueKind.Passthrough => spec.TypeFqn.EndsWith("Avm1Object", StringComparison.Ordinal)
            ? $"{expression}.AsObject"
            : spec.TypeFqn.EndsWith("Avm1Array", StringComparison.Ordinal)
                ? $"{expression}.AsArray"
                : expression,
        _ => spec.Conv switch
        {
            ConvKind.String => $"{expression}.AsString",
            ConvKind.Boolean => $"{expression}.AsBoolean",
            ConvKind.Number => $"({spec.TypeFqn}){expression}.AsNumber",
            ConvKind.Enum => $"({spec.TypeFqn})(long){expression}.AsNumber",
            _ => "default!",
        },
    };

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, true);
}
