using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis.CSharp;
using ShockwaveFlash.SourceGenerators.Avm1.Models;

namespace ShockwaveFlash.SourceGenerators.Avm1;

internal static class Avm1ContextEmitter
{
    private const string Meta = "global::ShockwaveFlash.Avm1.Serialization.Metadata";
    private const string ContextBase = Meta + ".Avm1SerializerContext";
    private const string TypeInfo = Meta + ".Avm1TypeInfo";
    private const string PropertyInfo = Meta + ".Avm1PropertyInfo";
    private const string Services = Meta + ".Avm1MetadataServices";
    private const string ObjectValues = Meta + ".Avm1ObjectInfoValues";
    private const string PropertyValues = Meta + ".Avm1PropertyInfoValues";
    private const string Options = "global::ShockwaveFlash.Avm1.Serialization.Avm1SerializerOptions";
    private const string GeneratedCode = "[global::System.CodeDom.Compiler.GeneratedCode(\"ShockwaveFlash.SourceGenerators\", \"1.0.0\")]";

    public static string Emit(Avm1ContextModel model)
    {
        var builder = new IndentedStringBuilder()
            .AppendIndentedLine("// <auto-generated/>")
            .AppendIndentedLine("#nullable enable")
            .AppendLine();

        if (model.Namespace is not null)
            builder
                .AppendIndentedLine($"namespace {model.Namespace};")
                .AppendLine();

        var scopes = new Stack<IDisposable>();

        foreach (var containing in model.ContainingTypes)
        {
            builder.AppendIndentedLine($"partial {containing}");
            scopes.Push(builder.CreateScope());
        }

        builder.AppendIndentedLine($"{model.Accessibility} partial class {model.TypeName} : {ContextBase}");
        scopes.Push(builder.CreateScope());

        EmitConstructors(builder, model.TypeName);

        var dispatch = new List<Avm1RegistrationModel>();
        var seenTypes = new HashSet<string>(StringComparer.Ordinal);

        foreach (var registration in model.Registrations)
        {
            builder.AppendLine();
            EmitAccessor(builder, registration);

            if (seenTypes.Add(registration.TypeModel.FullyQualifiedName))
                dispatch.Add(registration);
        }

        builder.AppendLine();
        EmitGetTypeInfo(builder, dispatch);

        foreach (var registration in model.Registrations)
        {
            builder.AppendLine();
            EmitCreate(builder, registration);
        }

        while (scopes.Count > 0)
            scopes.Pop().Dispose();

        return builder.ToString();
    }

    private static void EmitConstructors(IndentedStringBuilder builder, string typeName)
    {
        builder
            .AppendIndentedLine(GeneratedCode)
            .AppendIndentedLine($"public static {typeName} Default {{ get; }} = new {typeName}();")
            .AppendLine()
            .AppendIndentedLine(GeneratedCode)
            .AppendIndentedLine($"public {typeName}() : base(null)")
            .AppendIndentedLine("{")
            .AppendIndentedLine("}")
            .AppendLine()
            .AppendIndentedLine(GeneratedCode)
            .AppendIndentedLine($"public {typeName}({Options}? options) : base(options)")
            .AppendIndentedLine("{")
            .AppendIndentedLine("}");
    }

    private static void EmitAccessor(IndentedStringBuilder builder, Avm1RegistrationModel registration)
    {
        var type = registration.TypeModel.FullyQualifiedName;
        var accessor = registration.AccessorName;

        builder
            .AppendIndentedLine($"private {TypeInfo}<{type}>? _{accessor};")
            .AppendIndentedLine(GeneratedCode)
            .AppendIndentedLine($"public {TypeInfo}<{type}> {accessor} => _{accessor} ??= Create_{accessor}(Options);");
    }

    private static void EmitGetTypeInfo(IndentedStringBuilder builder, IReadOnlyList<Avm1RegistrationModel> dispatch)
    {
        builder
            .AppendIndentedLine(GeneratedCode)
            .AppendIndentedLine($"public override {TypeInfo}? GetTypeInfo(global::System.Type type)");

        using (builder.CreateScope())
        {
            foreach (var registration in dispatch)
                builder.AppendIndentedLine($"if (type == typeof({registration.TypeModel.FullyQualifiedName})) return {registration.AccessorName};");

            builder.AppendLine();
            builder.AppendIndentedLine("return null;");
        }
    }

    private static void EmitCreate(IndentedStringBuilder builder, Avm1RegistrationModel registration)
    {
        var model = registration.TypeModel;
        var type = model.FullyQualifiedName;
        var argMembers = BuildArgumentOrder(model);

        builder
            .AppendIndentedLine(GeneratedCode)
            .AppendIndentedLine($"private static {TypeInfo}<{type}> Create_{registration.AccessorName}({Options} options)");

        using (builder.CreateScope())
        {
            builder.AppendIndentedLine($"return {Services}.CreateObjectInfo(options, new {ObjectValues}<{type}>");
            builder.AppendIndentedLine("{");
            builder.Indent();

            builder.AppendIndentedLine($"ConstructorFactory = static __args => {Construction(model, argMembers)},");
            builder.AppendIndentedLine($"ConstructorArguments = {StringArray(argMembers.Select(m => m.CSharpName))},");

            if (registration.BindingPath.Count > 0)
                builder.AppendIndentedLine($"BindingPath = {StringArray(registration.BindingPath)},");

            builder.AppendIndentedLine($"PropertyMetadataInitializer = static __options => new {PropertyInfo}[]");
            builder.AppendIndentedLine("{");
            builder.Indent();

            foreach (var member in model.Members)
                EmitProperty(builder, type, member);

            builder.Unindent();
            builder.AppendIndentedLine("},");

            builder.Unindent();
            builder.AppendIndentedLine("});");
        }
    }

    private static void EmitProperty(IndentedStringBuilder builder, string type, Avm1MemberModel member)
    {
        builder.AppendIndentedLine($"{Services}.CreatePropertyInfo(__options, new {PropertyValues}<{type}>");
        builder.AppendIndentedLine("{");
        builder.Indent();

        builder.AppendIndentedLine($"MemberName = {Literal(member.CSharpName)},");
        builder.AppendIndentedLine($"Avm1PropertyName = {Literal(member.Avm1Key)},");
        builder.AppendIndentedLine($"MemberType = typeof({member.DeclaredType}),");
        builder.AppendIndentedLine($"Getter = static __obj => (({type})__obj).{member.CSharpName},");

        if (member.MemberNullable)
            builder.AppendIndentedLine("Nullable = true,");
        if (member.ThrowIfMissing)
            builder.AppendIndentedLine("ThrowIfMissing = true,");
        if (IsValueScalar(member))
            builder.AppendIndentedLine("IsValueScalar = true,");

        builder.AppendIndentedLine("IsConstructorParameter = true,");

        builder.Unindent();
        builder.AppendIndentedLine("}),");
    }

    private static List<Avm1MemberModel> BuildArgumentOrder(Avm1TypeModel model)
    {
        var ordered = new List<Avm1MemberModel>();

        if (model.Construction == ConstructionKind.Constructor)
        {
            foreach (var name in model.ConstructorParameterOrder)
                ordered.Add(model.Members.First(m => string.Equals(m.CSharpName, name, StringComparison.Ordinal)));

            foreach (var member in model.Members)
            {
                if (member.IsSettable && !member.IsConstructorParameter)
                    ordered.Add(member);
            }

            return ordered;
        }

        foreach (var member in model.Members)
        {
            if (member.IsSettable)
                ordered.Add(member);
        }

        return ordered;
    }

    private static string Construction(Avm1TypeModel model, IReadOnlyList<Avm1MemberModel> argMembers)
    {
        var type = model.FullyQualifiedName;

        if (model.Construction == ConstructionKind.Constructor)
        {
            var constructorCount = model.ConstructorParameterOrder.Count;
            var constructorArgs = string.Join(", ", Enumerable.Range(0, constructorCount).Select(i => Cast(argMembers[i], i)));
            var initializers = Enumerable.Range(constructorCount, argMembers.Count - constructorCount)
                .Select(i => $"{argMembers[i].CSharpName} = {Cast(argMembers[i], i)}")
                .ToList();

            return initializers.Count == 0
                ? $"new {type}({constructorArgs})"
                : $"new {type}({constructorArgs}) {{ {string.Join(", ", initializers)} }}";
        }

        if (argMembers.Count == 0)
            return $"new {type}()";

        var assignments = Enumerable.Range(0, argMembers.Count).Select(i => $"{argMembers[i].CSharpName} = {Cast(argMembers[i], i)}");
        return $"new {type} {{ {string.Join(", ", assignments)} }}";
    }

    private static string Cast(Avm1MemberModel member, int index)
    {
        var slot = $"__args[{index.ToString(System.Globalization.CultureInfo.InvariantCulture)}]";

        if (!member.MemberNullable)
            return $"({member.DeclaredType})({slot})!";

        return member.DeclaredType.EndsWith("?", StringComparison.Ordinal)
            ? $"({member.DeclaredType})({slot})"
            : $"({member.DeclaredType}?)({slot})";
    }

    private static bool IsValueScalar(Avm1MemberModel member)
    {
        return member.Value.Kind == ValueKind.Scalar && member.Value.IsValueType && !member.MemberNullable;
    }

    private static string StringArray(IEnumerable<string> values)
    {
        return $"new string[] {{ {string.Join(", ", values.Select(Literal))} }}";
    }

    private static string Literal(string value)
    {
        return SymbolDisplay.FormatLiteral(value, true);
    }
}
